export const projects = [
  {
    id: 0,
    image: '/images/schabulogo.PNG',
    title: 'Schabu',
    year: '2021',
    description: "Schabu is an AI-based solution that automates the pre-screening of job applicants through a phone call with Abigail, our smart AI assistant. With Schabu, our clients hire smarter and faster, transforming the recruitment experience for both recruiters and applicants.",
    stacks: ['React', 'Azure', 'Node'],
    code: 'private',
    source: 'https://schabu.com/',
  },
  {
    id: 1,
    image: '/images/exercise-tracker.PNG',
    title: 'MERN - Exercise Tracker',
    year: '2021',
    description: "A tool for recording your exercises, info about the exercises are entered by the user, the application stores data on MongoDB, and displays them in a table. This project is made for self-learning MERN project.",
    stacks: ['MongoDB', 'Express', 'React', 'Node'],
    code: 'https://github.com/PX-Shuo/mern-exercise-tracker',
    source: 'localhost',
  },
  {
    id: 2,
    image: '/images/pwa.PNG',
    title: 'PWA - COVID19 Stats Tracker',
    year: '2021',
    description: "A Progressive Web Application which accepts country names from user input, then fetch COVID19 statistics about that country from external API and display it on the screen.",
    stacks: ['React'],
    code: 'https://github.com/PX-Shuo/pwa-covid19-tracker',
    source: 'https://romantic-panini-b0076a.netlify.app/',
  },
  {
    id: 3,
    image: '/images/java-db-customer.PNG',
    title: 'Customer Info Database',
    year: '2019',
    description: "A school project I did during my Master\'s degree study, made using Java. This program is able to connect to UTS' student-use database and perform CRUD operations, it also has an user interface for input data and perform CRUD commands, this GUI is made using WindowBuilder",
    stacks: ['Java', 'MYSQL'],
    code: 'https://github.com/PX-Shuo/customer-info-db',
    source: 'localhost',
  },
  {
    id: 4,
    image: '/images/consoleapp.jpg',
    title: 'Console App - Bank System',
    year: '2019',
    description: "A school project I did during my Master\'s degree study, made using .Net. It is a simple console application which simulates bank system, you can create accouts, make deposit or withdraw, and etc. Please check the demo video for more details.",
    stacks: ['C#'],
    code: 'https://github.com/PX-Shuo/consoleapp-banksystem',
    source: 'https://youtu.be/b3wHp9YyVWo',
  },
  {
    id: 5,
    image: '/images/unitygame.PNG',
    title: 'Unity - 3D Game',
    year: '2019',
    description: "A school project I did during my Master\'s degree study, made using Unity. It is a 3D game, aiming to kick the balls into the goals to pass each stage, while there are some monsters hunting you. Please check the demo video for more details.",
    stacks: ['Unity','C#'],
    code: 'https://github.com/PX-Shuo/uniproject-unitygame',
    source: 'https://youtu.be/fOffEGuqwKo',
  },
];

export const TimeLineData = [
  { year: 2021, text: 'Started working as an Web Developer Intern at AI Australia', },
  { year: 2020, text: 'Completed Master\'s degree', },
  { year: 2019, text: 'Started Master study at UTS', },
  { year: 2018, text: 'Graduated from Western Sydney University', },
];